name: Build Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Get Plugin Version
        id: version
        run: |
          VERSION=$(grep '^version' build.gradle.kts | sed -E 's/^version[[:space:]]*=[[:space:]]*"([^"]*)".*/\1/')
          echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: artifact-bos-project-init-tool-${{ steps.version.outputs.VERSION }}
          path: build/distributions/bos-project-init-tool-*.zip
